service: star-super-auth
plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  memorySize: 256
  timeout: 10

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

functions:
  auth:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
